openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/addPatient:
    post:
      tags:
        - patient-controller
      operationId: insertPatient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  /api/patientsStartsWith/{firstNameStartsWith}:
    get:
      tags:
        - patient-controller
      operationId: getPatientStartsWith
      parameters:
        - name: firstNameStartsWith
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  /api/getPatient/{startYear}/{endYear}:
    get:
      tags:
        - patient-controller
      operationId: getPatientCountYearRange
      parameters:
        - name: startYear
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: endYear
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int64
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  /api/getPatient/{id}:
    get:
      tags:
        - patient-controller
      operationId: getPatientWithId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  /api/allPatients:
    get:
      tags:
        - patient-controller
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Patient:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date-time
